# Generated by Django 4.1.1 on 2022-10-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(upload_to='movies/templates/movies/movie_cover_pictures'),
        ),
    ]
